---

- include: install_additional_packages.yml
  tags: packages

- include: create_users_and_groups.yml

- include: setup_supervisor.yml
  tags: supervisor

- include: set_file_permissions.yml
  tags: deploy

- include: setup_nginx.yml
  tags: nginx